issues:
  max-same-issues: 0
  max-issues-per-linter: 0

linters:
  disable-all: true
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - execinquery
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - loggercheck
    - misspell
    - mirror
    - nilerr
    - nilnil
    - noctx
    - paralleltest
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tenv
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars

linters-settings:
  errcheck:
    exclude-functions:
      - (go.uber.org/zap/zapcore.ObjectEncoder).AddObject
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/capnspacehook/whalewall)
  misspell:
    locale: US
  paralleltest:
    ignore-missing: true
  revive:
    rules:
      - name: blank-imports
        disabled: true
