// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package database

import (
	"context"
)

type Querier interface {
	ActivateWaitingContainerRules(ctx context.Context, dstContainerName string) error
	AddContainer(ctx context.Context, arg AddContainerParams) error
	AddContainerAddr(ctx context.Context, arg AddContainerAddrParams) error
	AddContainerAlias(ctx context.Context, arg AddContainerAliasParams) error
	AddEstContainer(ctx context.Context, arg AddEstContainerParams) error
	AddWaitingContainerRule(ctx context.Context, arg AddWaitingContainerRuleParams) error
	ContainerExists(ctx context.Context, id string) (interface{}, error)
	DeactivateWaitingContainerRules(ctx context.Context, dstContainerName string) error
	DeleteContainer(ctx context.Context, id string) error
	DeleteContainerAddrs(ctx context.Context, containerID string) error
	DeleteContainerAliases(ctx context.Context, containerID string) error
	DeleteEstContainers(ctx context.Context, arg DeleteEstContainersParams) error
	DeleteWaitingContainerRules(ctx context.Context, srcContainerID string) error
	GetContainerAddrs(ctx context.Context, containerID string) ([][]byte, error)
	GetContainerID(ctx context.Context, name string) (string, error)
	GetContainerIDAndNameFromAlias(ctx context.Context, containerAlias string) (Container, error)
	GetContainerName(ctx context.Context, id string) (string, error)
	GetContainers(ctx context.Context) ([]Container, error)
	GetEstContainers(ctx context.Context, srcContainerID string) ([]GetEstContainersRow, error)
	GetWaitingContainerRules(ctx context.Context, dstContainerName string) ([]GetWaitingContainerRulesRow, error)
}

var _ Querier = (*Queries)(nil)
