name: Check generated files

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "00 13 * * 1"

  workflow_dispatch: {}

jobs:
  check-go-generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Export constant environmental variables
        uses: cardinalby/export-env-action@v2
        with:
          envFile: .github/constants.env

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}.x
          check-latest: true
          cache: true

      - name: Ensure 'go generate' is clean
        run: |
          # shellcheck disable=SC2046
          go generate $(go list ./...)
          echo
          echo

          if ! git diff --name-only --exit-code; then
            echo "The files above need updating. Please run 'go generate'."
            exit 1
          fi
