name: Check generated files

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "00 13 * * 1"

  workflow_dispatch: {}

jobs:
  check-generated:
    permissions:
      contents: read
    uses: capnspacehook/go-workflows/.github/workflows/check-generated.yml@master
